Now checks for GIT together with other dependencies.

diff --git a/krudt b/krudt
--- a/krudt
+++ b/krudt
@@ -17,6 +17,12 @@ then
     exit 255
 fi
 
+if [ -z `which git` ]
+then
+    echo "Missing git"
+    exit 255
+fi
+
 if [ $# != 1 ]
 then
   echo "USAGE: $0 NAME"
